global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ocr-service"
    static_configs:
      - targets: ["ocr-service:8000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "b2b-api"
    static_configs:
      - targets: ["b2b-api:8001"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: "/nginx_status"
    scrape_interval: 30s
