app = "receiptradar-ocr"
primary_region = "akl"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096

[mounts]
  source = "receiptradar_ocr_data"
  destination = "/app/data"

[metrics]
  port = 9091
  path = "/metrics" 