// Comprehensive product categorization system for ReceiptRadar
// This provides much better categorization than just "general"

export interface ProductCategory {
  id: string;
  name: string;
  description: string;
  color: string;
  icon: string;
  keywords: string[];
  subcategories?: string[];
  imageUrl: string;
}

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  // Fresh Produce
  {
    id: "fresh-produce",
    name: "Fresh Produce",
    description: "Fresh fruits, vegetables, and herbs",
    color: "#4CAF50",
    icon: "local-florist",
    imageUrl:
      "https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=400&h=300&fit=crop&q=80",
    keywords: [
      "apple",
      "banana",
      "orange",
      "grape",
      "strawberry",
      "blueberry",
      "raspberry",
      "tomato",
      "lettuce",
      "carrot",
      "onion",
      "potato",
      "avocado",
      "cucumber",
      "pepper",
      "broccoli",
      "cauliflower",
      "spinach",
      "kale",
      "cabbage",
      "celery",
      "mushroom",
      "garlic",
      "ginger",
      "lemon",
      "lime",
      "grapefruit",
      "pear",
      "peach",
      "plum",
      "cherry",
      "mango",
      "pineapple",
      "watermelon",
      "cantaloupe",
      "honeydew",
      "kiwi",
      "passion fruit",
      "feijoa",
      "tamarillo",
      "fresh",
      "organic",
      "local",
      "seasonal",
      "herbs",
      "basil",
      "parsley",
      "cilantro",
      "mint",
      "rosemary",
      "thyme",
      "oregano",
      "sage",
      "dill",
    ],
    subcategories: ["fruits", "vegetables", "herbs", "organic"],
  },

  // Dairy & Eggs
  {
    id: "dairy",
    name: "Dairy & Eggs",
    description: "Milk, cheese, yogurt, butter, and eggs",
    color: "#2196F3",
    icon: "local-drink",
    imageUrl:
      "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=300&fit=crop&q=80",
    keywords: [
      "milk",
      "cheese",
      "yogurt",
      "yoghurt",
      "butter",
      "cream",
      "egg",
      "eggs",
      "cheddar",
      "mozzarella",
      "feta",
      "parmesan",
      "brie",
      "camembert",
      "gouda",
      "swiss",
      "provolone",
      "ricotta",
      "cottage cheese",
      "cream cheese",
      "sour cream",
      "whipping cream",
      "heavy cream",
      "half and half",
      "almond milk",
      "soy milk",
      "oat milk",
      "coconut milk",
      "lactose free",
      "organic milk",
      "free range eggs",
      "barn eggs",
      "cage free",
    ],
    subcategories: ["milk", "cheese", "yogurt", "eggs", "plant-based"],
  },

  // Meat & Seafood
  {
    id: "meat-seafood",
    name: "Meat & Seafood",
    description: "Fresh meat, poultry, fish, and seafood",
    color: "#F44336",
    icon: "restaurant",
    imageUrl:
      "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=300&fit=crop&q=80",
    keywords: [
      "beef",
      "chicken",
      "pork",
      "lamb",
      "turkey",
      "duck",
      "fish",
      "salmon",
      "tuna",
      "cod",
      "hoki",
      "snapper",
      "gurnard",
      "trevally",
      "kingfish",
      "steak",
      "mince",
      "ground beef",
      "sausage",
      "bacon",
      "ham",
      "prosciutto",
      "salami",
      "pepperoni",
      "chorizo",
      "pork belly",
      "pork chops",
      "lamb chops",
      "lamb shoulder",
      "lamb leg",
      "chicken breast",
      "chicken thigh",
      "chicken wing",
      "drumstick",
      "whole chicken",
      "organic meat",
      "free range",
      "grass fed",
      "shrimp",
      "prawn",
      "mussel",
      "oyster",
      "clam",
      "scallop",
      "crab",
      "lobster",
    ],
    subcategories: ["beef", "poultry", "pork", "lamb", "fish", "seafood"],
  },

  // Bread & Bakery
  {
    id: "bread-bakery",
    name: "Bread & Bakery",
    description: "Fresh bread, pastries, and baked goods",
    color: "#FF9800",
    icon: "bakery-dining",
    imageUrl:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop&q=80",
    keywords: [
      "bread",
      "sourdough",
      "roll",
      "bun",
      "toast",
      "sandwich",
      "bagel",
      "croissant",
      "pastry",
      "muffin",
      "cupcake",
      "cake",
      "cookie",
      "biscuit",
      "donut",
      "doughnut",
      "pie",
      "tart",
      "eclair",
      "danish",
      "pain au chocolat",
      "white bread",
      "whole wheat",
      "whole grain",
      "multigrain",
      "rye bread",
      "ciabatta",
      "focaccia",
      "naan",
      "pita",
      "tortilla",
      "wraps",
      "flatbread",
      "artisan",
      "fresh baked",
      "bakery",
    ],
    subcategories: ["bread", "pastries", "cakes", "cookies"],
  },

  // Pantry & Staples
  {
    id: "pantry-staples",
    name: "Pantry & Staples",
    description: "Dry goods, canned foods, and cooking essentials",
    color: "#795548",
    icon: "kitchen",
    imageUrl:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop&q=80",
    keywords: [
      "pasta",
      "rice",
      "flour",
      "sugar",
      "oil",
      "sauce",
      "soup",
      "cereal",
      "baking",
      "baking powder",
      "baking soda",
      "yeast",
      "salt",
      "pepper",
      "spices",
      "herbs",
      "garlic powder",
      "onion powder",
      "paprika",
      "cumin",
      "oregano",
      "basil",
      "thyme",
      "rosemary",
      "bay leaves",
      "cinnamon",
      "nutmeg",
      "vanilla",
      "chocolate",
      "cocoa",
      "honey",
      "maple syrup",
      "jam",
      "jelly",
      "peanut butter",
      "nutella",
      "marmite",
      "vegemite",
      "beans",
      "lentils",
      "chickpeas",
      "kidney beans",
      "black beans",
      "tomato sauce",
      "pasta sauce",
      "soy sauce",
      "fish sauce",
      "vinegar",
      "mustard",
      "mayonnaise",
      "ketchup",
      "hot sauce",
      "sriracha",
    ],
    subcategories: ["grains", "canned goods", "condiments", "spices", "baking"],
  },

  // Beverages
  {
    id: "beverages",
    name: "Beverages",
    description: "Drinks, juices, sodas, and alcoholic beverages",
    color: "#9C27B0",
    icon: "local-cafe",
    imageUrl:
      "https://images.unsplash.com/photo-1546173159-315724a31696?w=400&h=300&fit=crop&q=80",
    keywords: [
      "water",
      "juice",
      "soda",
      "beer",
      "wine",
      "coffee",
      "tea",
      "coke",
      "pepsi",
      "sparkling",
      "fizzy",
      "lemonade",
      "orange juice",
      "apple juice",
      "cranberry juice",
      "grape juice",
      "tomato juice",
      "vegetable juice",
      "smoothie",
      "milkshake",
      "hot chocolate",
      "energy drink",
      "sports drink",
      "red bull",
      "monster",
      "v",
      "powerade",
      "gatorade",
      "coconut water",
      "almond milk",
      "soy milk",
      "oat milk",
      "rice milk",
      "hot tea",
      "green tea",
      "black tea",
      "herbal tea",
      "chamomile",
      "peppermint",
      "earl grey",
      "english breakfast",
      "instant coffee",
      "ground coffee",
      "coffee beans",
      "espresso",
      "cappuccino",
      "latte",
      "mocha",
    ],
    subcategories: ["soft drinks", "juices", "coffee", "tea", "alcohol"],
  },

  // Snacks & Confectionery
  {
    id: "snacks-confectionery",
    name: "Snacks & Confectionery",
    description: "Chips, nuts, chocolate, candy, and snack foods",
    color: "#FF5722",
    icon: "cake",
    imageUrl:
      "https://images.unsplash.com/photo-1517686469429-8bdb88b9f907?w=400&h=300&fit=crop&q=80",
    keywords: [
      "chips",
      "crackers",
      "nuts",
      "chocolate",
      "candy",
      "biscuits",
      "cookies",
      "popcorn",
      "pretzels",
      "trail mix",
      "granola",
      "energy bar",
      "protein bar",
      "muesli bar",
      "fruit bar",
      "dried fruit",
      "raisins",
      "apricots",
      "prunes",
      "dates",
      "figs",
      "almonds",
      "walnuts",
      "cashews",
      "peanuts",
      "pistachios",
      "macadamia",
      "pecans",
      "sunflower seeds",
      "pumpkin seeds",
      "chia seeds",
      "flax seeds",
      "sesame seeds",
      "dark chocolate",
      "milk chocolate",
      "white chocolate",
      "lollies",
      "sweets",
      "gummies",
      "jelly beans",
      "marshmallows",
      "licorice",
      "toffee",
      "caramel",
      "fudge",
      "truffles",
      "pralines",
      "bonbons",
    ],
    subcategories: ["chips", "nuts", "chocolate", "candy", "dried fruits"],
  },

  // Frozen Foods
  {
    id: "frozen-foods",
    name: "Frozen Foods",
    description: "Frozen meals, vegetables, and desserts",
    color: "#00BCD4",
    icon: "ac-unit",
    imageUrl:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&q=80",
    keywords: [
      "ice cream",
      "frozen",
      "pizza",
      "fries",
      "peas",
      "corn",
      "icecream",
      "frozen vegetables",
      "frozen fruit",
      "frozen berries",
      "frozen fish",
      "frozen meat",
      "frozen chicken",
      "frozen beef",
      "frozen pork",
      "frozen meals",
      "tv dinner",
      "ready meal",
      "frozen lasagna",
      "frozen pasta",
      "frozen rice",
      "frozen potatoes",
      "frozen chips",
      "frozen waffles",
      "frozen pancakes",
      "frozen bread",
      "frozen pastry",
      "frozen dessert",
      "ice cream sandwich",
      "ice cream bar",
      "popsicle",
      "sorbet",
      "gelato",
      "frozen yogurt",
      "frozen smoothie",
      "frozen juice",
    ],
    subcategories: ["frozen meals", "frozen vegetables", "frozen desserts"],
  },

  // Household & Cleaning
  {
    id: "household-cleaning",
    name: "Household & Cleaning",
    description: "Cleaning supplies, paper products, and household items",
    color: "#607D8B",
    icon: "home",
    imageUrl:
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop&q=80",
    keywords: [
      "toilet paper",
      "paper towel",
      "tissue",
      "napkins",
      "paper napkins",
      "detergent",
      "laundry",
      "fabric softener",
      "bleach",
      "dish soap",
      "dishwasher",
      "cleaning",
      "all purpose cleaner",
      "window cleaner",
      "bathroom cleaner",
      "kitchen cleaner",
      "floor cleaner",
      "carpet cleaner",
      "air freshener",
      "deodorizer",
      "trash bags",
      "garbage bags",
      "ziploc",
      "plastic wrap",
      "aluminum foil",
      "parchment paper",
      "wax paper",
      "paper plates",
      "plastic cups",
      "paper cups",
      "plastic utensils",
      "paper utensils",
      "matches",
      "lighters",
      "batteries",
      "light bulbs",
    ],
    subcategories: [
      "paper products",
      "cleaning supplies",
      "laundry",
      "storage",
    ],
  },

  // Personal Care & Health
  {
    id: "personal-care-health",
    name: "Personal Care & Health",
    description: "Toiletries, health products, and personal hygiene items",
    color: "#E91E63",
    icon: "spa",
    imageUrl:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop&q=80",
    keywords: [
      "shampoo",
      "conditioner",
      "soap",
      "body wash",
      "hand soap",
      "toothpaste",
      "toothbrush",
      "dental floss",
      "mouthwash",
      "deodorant",
      "antiperspirant",
      "lotion",
      "moisturizer",
      "sunscreen",
      "suntan lotion",
      "lip balm",
      "chapstick",
      "razor",
      "shaving cream",
      "shaving gel",
      "aftershave",
      "perfume",
      "cologne",
      "makeup",
      "cosmetics",
      "foundation",
      "concealer",
      "powder",
      "blush",
      "eyeshadow",
      "mascara",
      "eyeliner",
      "lipstick",
      "nail polish",
      "nail polish remover",
      "cotton balls",
      "cotton swabs",
      "q tips",
      "band aids",
      "adhesive bandages",
      "pain reliever",
      "aspirin",
      "ibuprofen",
      "acetaminophen",
      "vitamins",
      "supplements",
      "probiotics",
    ],
    subcategories: ["hair care", "skin care", "oral care", "makeup", "health"],
  },

  // Baby & Kids
  {
    id: "baby-kids",
    name: "Baby & Kids",
    description: "Baby food, diapers, and children's products",
    color: "#FFC107",
    icon: "child-care",
    imageUrl:
      "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&h=300&fit=crop&q=80",
    keywords: [
      "diaper",
      "nappy",
      "baby food",
      "formula",
      "baby formula",
      "baby milk",
      "baby cereal",
      "baby snacks",
      "baby wipes",
      "baby lotion",
      "baby shampoo",
      "baby soap",
      "baby oil",
      "baby powder",
      "baby cream",
      "baby medicine",
      "teething",
      "pacifier",
      "bottle",
      "sippy cup",
      "baby spoon",
      "baby fork",
      "baby bowl",
      "baby plate",
      "baby bib",
      "baby towel",
      "baby washcloth",
      "baby blanket",
      "baby clothes",
      "onesie",
      "baby socks",
      "baby shoes",
      "baby hat",
      "baby mittens",
      "baby toys",
      "rattle",
      "teether",
      "stroller",
      "car seat",
      "high chair",
      "crib",
      "bassinet",
      "changing table",
    ],
    subcategories: ["diapers", "baby food", "baby care", "baby accessories"],
  },

  // Pet Supplies
  {
    id: "pet-supplies",
    name: "Pet Supplies",
    description: "Pet food, treats, and pet care products",
    color: "#8BC34A",
    icon: "pets",
    imageUrl:
      "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400&h=300&fit=crop&q=80",
    keywords: [
      "dog food",
      "cat food",
      "pet food",
      "dog treats",
      "cat treats",
      "pet treats",
      "dog toy",
      "cat toy",
      "pet toy",
      "dog collar",
      "cat collar",
      "pet collar",
      "dog leash",
      "cat leash",
      "pet leash",
      "dog bed",
      "cat bed",
      "pet bed",
      "dog bowl",
      "cat bowl",
      "pet bowl",
      "dog shampoo",
      "cat shampoo",
      "pet shampoo",
      "flea treatment",
      "tick treatment",
      "worm treatment",
      "pet medicine",
      "litter",
      "cat litter",
      "litter box",
      "scratching post",
      "cat tree",
      "dog crate",
      "pet carrier",
      "pet brush",
      "pet comb",
      "pet nail clippers",
    ],
    subcategories: ["dog supplies", "cat supplies", "pet food", "pet care"],
  },

  // Alcohol & Tobacco
  {
    id: "alcohol-tobacco",
    name: "Alcohol & Tobacco",
    description: "Beer, wine, spirits, and tobacco products",
    color: "#3F51B5",
    icon: "local-bar",
    imageUrl:
      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop&q=80",
    keywords: [
      "beer",
      "wine",
      "spirits",
      "liquor",
      "vodka",
      "rum",
      "whiskey",
      "whisky",
      "gin",
      "tequila",
      "brandy",
      "cognac",
      "liqueur",
      "schnapps",
      "absinthe",
      "red wine",
      "white wine",
      "rose wine",
      "sparkling wine",
      "champagne",
      "prosecco",
      "cava",
      "lager",
      "ale",
      "stout",
      "porter",
      "pilsner",
      "cigarettes",
      "cigars",
      "tobacco",
      "rolling papers",
      "lighters",
      "matches",
      "pipe tobacco",
      "smoking",
      "vape",
      "e-cigarette",
    ],
    subcategories: ["beer", "wine", "spirits", "tobacco"],
  },

  // Organic & Health Foods
  {
    id: "organic-health",
    name: "Organic & Health Foods",
    description: "Organic products, health foods, and dietary supplements",
    color: "#4CAF50",
    icon: "eco",
    imageUrl:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&q=80",
    keywords: [
      "organic",
      "natural",
      "gluten free",
      "dairy free",
      "lactose free",
      "vegan",
      "vegetarian",
      "plant based",
      "non gmo",
      "gmo free",
      "sugar free",
      "low carb",
      "keto",
      "paleo",
      "whole grain",
      "whole wheat",
      "sprouted",
      "fermented",
      "probiotic",
      "prebiotic",
      "superfood",
      "chia seeds",
      "flax seeds",
      "hemp seeds",
      "quinoa",
      "amaranth",
      "buckwheat",
      "millet",
      "teff",
      "sorghum",
      "spelt",
      "kamut",
      "nutritional yeast",
      "spirulina",
      "chlorella",
      "moringa",
      "matcha",
      "turmeric",
      "ginger",
      "garlic",
      "onion",
      "lemon",
      "lime",
    ],
    subcategories: ["organic", "gluten-free", "vegan", "supplements"],
  },
];

// Helper function to categorize a product
export function categorizeProduct(productName: string): ProductCategory {
  const lowerName = productName.toLowerCase();

  // Find the best matching category
  let bestMatch: ProductCategory | null = null;
  let bestScore = 0;

  for (const category of PRODUCT_CATEGORIES) {
    let score = 0;

    // Check for exact keyword matches
    for (const keyword of category.keywords) {
      if (lowerName.includes(keyword.toLowerCase())) {
        score += 2; // Higher weight for exact matches
      }
    }

    // Check for partial matches
    for (const keyword of category.keywords) {
      const keywordWords = keyword.split(" ");
      for (const word of keywordWords) {
        if (word.length > 2 && lowerName.includes(word.toLowerCase())) {
          score += 1; // Lower weight for partial matches
        }
      }
    }

    if (score > bestScore) {
      bestScore = score;
      bestMatch = category;
    }
  }

  // Return the best match or a default category
  return (
    bestMatch || PRODUCT_CATEGORIES.find((cat) => cat.id === "pantry-staples")!
  );
}

// Helper function to get category by ID
export function getCategoryById(id: string): ProductCategory | undefined {
  return PRODUCT_CATEGORIES.find((category) => category.id === id);
}

// Helper function to get all categories
export function getAllCategories(): ProductCategory[] {
  return PRODUCT_CATEGORIES;
}

// Helper function to get category image
export function getCategoryImage(categoryId: string): string {
  const category = getCategoryById(categoryId);
  return category?.imageUrl || PRODUCT_CATEGORIES[0].imageUrl;
}
